raystack/frontier

Dockerfile.dev
docker-compose.yml
package.json

Creating a separate Dockerfile for development as in the current one, we run the `build` command to transpile the TS code to JS, which is not needed as we started using `ts-node` for development.

Setup Dockerfile for development.

---

src/app/policy/resource.ts
src/app/user/resource.ts
test/app/user/resource.ts

In `Get Users` api when we apply the `role.tags` filter on the `policies` field, it is filtering the User list, not the subfield.
This happened due to the 'Where` clause is getting applied on the Users list.
So instead of doing that we can filter the casbin_rule policies at the time of aggregation.
This fix also adds support to pass multiple role tags in the query.

fix: policy filter in get all user api

---

api/handler/v1/org.go
api/handler/v1/org_test.go
api/handler/v1/project.go
api/handler/v1/project_test.go
api/handler/v1/util.go
api/handler/v1/v1.go
cmd/serve_api.go
internal/org/org.go
internal/project/project.go
model/model.go
model/v1/v1.go
store/postgres/migrations/20211020192111_create_organization_table.up.sql
store/postgres/migrations/20211028230242_create_projects_table.down.sql
store/postgres/migrations/20211028230242_create_projects_table.up.sql
store/postgres/org.go
store/postgres/projects.go

feat: add projects api

---

cmd/serve_proxy.go
config/config.go
go.mod
go.sum
integration/fixtures/ruleset.grpc.yaml
integration/fixtures/ruleset.rest.yaml
integration/rest_test.go
middleware/authz/authz.go
middleware/grpc_payload.go
middleware/middleware.go
middleware/rulematch/regex_matcher.go
middleware/rulematch/route_matcher.go
middleware/rulematch/rulematch.go
proxy/roundtripper.go
rules/sample.rest.yaml
store/blob/rule_repository.go
structs/rule.go

1.Issue where we cannot use proxy for http & http2. This just works for h2c & grpc.
Solving this by using different RoundTrippers for grpc and others
Tested this for
<br>
2. Extract required attributes from request
<br>
3. Use gorilla.mux instead of regex to match rules
<br>
<br>
4. Change rule yaml format
```yaml
rules:
- backends:
- name: firehose
target: "http://localhost:3030"
frontends:
- action: READ_FIREHOSE
path: "/v2/firehose"
method: "POST"
middlewares:
- name: authz
config:
attributes:
project:
type: json_payload
key: id.project
- name: test2
path: "/v2/firehose"
method: "GET"
middlewares:
- name: authz
config:
attributes:
project:
type: json_payload
key: id.project
- name: dagger
target: "http://localhost:3030/new"
frontends:
- action: READ_FIREHOSE
path: "/v2/dagger"
method: …
```

feat: proxy Setup

---

hook/authz/authz.go
proxy/roundtripper.go

fix: escape from hook when resp is >= 400 and disable decoding

---

resources_config/resources.yaml
store/blob/resources_repository.go

Using a new format to define namespaces, which will be combined with resource_type
```yaml
backends:
- name: guardian
resource_types:
- name: "appeal"
actions:
read:
- owner
delete:
- owner
- name: "provider"
actions:
read:
- owner
- "organization.organization_admin"
write:
- owner
```

use a format to combine resource type in namespaces

---

api/handler/v1beta1/group.go
api/handler/v1beta1/org.go
api/handler/v1beta1/util.go
api/handler/v1beta1/v1.go

Currently, shield returns an `internal server error` response when an unauthorized user tries to make an action. I am proposing to change the response to
```
{
"code": 7,
"message": "permission denied",
"details": []
}
```
`PermissionDenied Code = 7`
Wdyt @rsbh @krtkvrm ?

feat: change error msg for unauthorized actions

---

internal/authz/authz.go
internal/authz/spicedb/spicedb.go
internal/permission/relation.go
internal/resource/resource.go
resources_config/resources.yaml
store/postgres/migrations/20220523150122_create_constraint_resource_urn.down.sql
store/postgres/migrations/20220523150122_create_constraint_resource_urn.up.sql
store/postgres/resource.go

Changing the behaviour of creating resource from hooks from `insert` to `upsert`. This can support both POST and PUT

feat: upsert the relationship from authz hook

---

api/handler/v1beta1/group.go

As a non-admin User, tried to remove/add another user from a group, as expected Shield throws here an unauthorized error. But the API handler layer does not capture the error and throws grcpInternalError and its result to 500 HTTP error code in response.

fix: Handle shield unauthorized error

---

core/bootstrap/bootstrap.go
core/bootstrap/bootstrap_test.go

fix: error in bootstrapping shield from fresh database

---

Dockerfile.dev

We use Dockerfile.dev to build a tag dev. Our current Dockerfile.dev copied shield to /usr/local/bin/shield but the Dockerfile is copying shield to usr/bin/shield.
We expect the same path between Dockerfile and Dockerfile.dev. We need to update Dockerfile.dev so shield is copied to /usr/bin/shield.
**Changes**
- Copy shield to `usr/bin`
- Add `glibc` for compatibility purpose

fix: dockerfile dev file

---

core/role/service.go
internal/api/v1beta1/group.go
internal/api/v1beta1/namespace.go
internal/api/v1beta1/policy.go
internal/api/v1beta1/role.go
internal/store/postgres/group_repository.go
internal/store/postgres/group_repository_test.go

- `ListUserGroups` should not make `roleId` mandatory
- `Create` and `Update` role service should return error if any
-  `Create` and `Update` group handler should pass both `Organization` and `OrganizationID`
- `UpdateRole` and `UpdateNamespace` ID should be immutable
- Wrong placement of switch case in `UpdatePolicy` handler

fix: bug in group, role, and policy

---

docker-compose.yml
internal/proxy/context.go
internal/proxy/roundtripper.go

feat: prevent proxy context cancelled

---

cmd/serve.go
cmd/server.go
core/namespace/namespace.go
core/resource/resource.go
internal/store/spicedb/spicedb.go
test/e2e_test/helper_test.go
test/e2e_test/smoke_test.go
test/e2e_test/testbench/postgres.go
test/e2e_test/testbench/shield.go
test/e2e_test/testbench/spicedb.go
test/e2e_test/testbench/testbench.go
test/e2e_test/testdata/configs/resources/resources.yaml
test/e2e_test/testdata/configs/rules/rules.yaml
test/e2e_test/testdata/mocks/mock-group.json
test/e2e_test/testdata/mocks/mock-organization.json
test/e2e_test/testdata/mocks/mock-project.json
test/e2e_test/testdata/mocks/mock-user.json

Add utility to do end-to-end test
- Spin up 2 Postgres and 1 Spice DB in such a way that they are connected
- All are being done programmatically with dockertest
- Once all DBs are up, run shield migration and shield server with `cobra cli`

feat: add e2e test bench

---

cmd/serve_proxy.go
internal/proxy/hook/authz/authz.go
internal/proxy/hook/authz/authz_test.go
internal/proxy/middleware/attributes/attributes.go
internal/proxy/middleware/attributes/attributes_test.go
internal/proxy/middleware/attributes/context.go
internal/proxy/middleware/authz/authz.go
internal/proxy/middleware/prefix/prefix.go
test/integration_test/grpc_test.go
test/integration_test/rest_test.go

Created a new layer for attribute extraction right after `rulematch`.
It pushes all the attributes into the context for the use of middleware and hook.
Current flow: Request -> [Middleware starts] Rule Matching -> Basic Auth -> Authz -> Prefix -> Backend -> [Hook starts] Authz -> Response
Modified flow with this PR: Request -> [Middleware starts] Rule Matching -> **_Attribute Extraction_** -> Basic Auth -> Authz -> Prefix -> Backend -> [Hook starts] Authz -> Response
Closes #157

feat: streamline attribute extraction in middleware and hooks

---

core/resource/service.go
internal/proxy/middleware/authz/authz.go

Currently, shield proxy's auth middleware returns 401 even when a resource doesn't exist.
This PR will change the error code to `404 not found` for this scenario.

feat: authz middleware to return 404 when resource not found

---

config/config.go

Shield already supports taking configs from env but the cli fails if it didn't find a config file locally. It should either add validation to check if configs are present or continue the execution.

fix: don't fail for missing configuration file

---

config/config.yaml
core/user/errors.go
go.mod
go.sum
internal/api/v1beta1/user.go
internal/proxy/hook/authz/authz.go
internal/server/config.go
internal/server/server.go
internal/store/postgres/user_repository.go
pkg/telemetry/opencensus.go
pkg/telemetry/telemetry.go

feat: code instrumentation

---

Makefile
cmd/serve.go
core/authenticate/authenticate.go
core/authenticate/registration_flow.go
core/authenticate/session_service.go
docs/README.md
docs/docs/reference/api.md
docs/docs/reference/cli.md
docs/docs/reference/configurations.md
docs/docs/tour/setup-server.md
docs/yarn.lock
internal/api/v1beta1/authenticate.go
internal/api/v1beta1/mocks/session_service.go
internal/store/postgres/flow.go
internal/store/postgres/flow_repository.go
internal/store/postgres/migrations/20230407163624_create_session_table.down.sql
internal/store/postgres/migrations/20230407163624_create_session_table.up.sql
internal/store/postgres/migrations/20230410103624_create_flows_table.down.sql
internal/store/postgres/migrations/20230410103624_create_flows_table.up.sql
internal/store/postgres/postgres.go
internal/store/postgres/session.go
internal/store/postgres/session_repository.go

- Update API and CLI reference
- Update server configurations

feat(authentication): add support to persist sessions and flows in database

---

core/authenticate/context.go
core/authenticate/service.go
core/serviceuser/errors.go
core/serviceuser/filter.go
core/serviceuser/service.go
core/serviceuser/serviceuser.go
go.mod
go.sum
internal/api/v1beta1/serviceuser.go
internal/store/postgres/serviceuser.go
internal/store/postgres/serviceuser_credential_repository.go
internal/store/postgres/user_repository.go
pkg/server/consts/gateway.go
pkg/server/interceptors/session.go
test/e2e/regression/serviceusers_test.go

Serviceusers can now send base64 encoded `clientid:clientsecret` in `Authorization` header as `Basic <val>` to authenticate.

feat: service user client id-secret support

---

cmd/serve.go
config/config.go
config/sample.config.yaml
core/authenticate/config.go
docs/docs/reference/configurations.md
pkg/server/config.go
pkg/server/consts/gateway.go
pkg/server/interceptors/cors.go
pkg/server/interceptors/session.go
pkg/server/server.go
test/e2e/regression/authentication_test.go

- few session variables are also exposed as config

feat: allow configuring cors middleware

---

cmd/serve.go
config/sample.config.yaml
core/organization/errors.go
core/organization/service.go
docs/docs/configurations.md
docs/docs/reference/configurations.md
internal/api/v1beta1/audit.go
internal/api/v1beta1/audit_test.go
internal/api/v1beta1/domain.go
internal/api/v1beta1/domain_test.go
internal/api/v1beta1/group.go
internal/api/v1beta1/group_test.go
internal/api/v1beta1/invitations.go
internal/api/v1beta1/invitations_test.go
internal/api/v1beta1/mocks/organization_service.go
internal/api/v1beta1/org.go
internal/api/v1beta1/org_test.go
internal/store/postgres/organization_repository.go
pkg/server/config.go
test/e2e/regression/api_test.go

-  Disable org on creation flag added. 
- Org APIs now accepts both org name and uuid. Have added checks to prevent actions on disabled orgs
- Additionally a check to prevent the last org admin and project owner to be removed. Another user must be given these permissions before removing that user

feat: add disable org on creation flag and disallow removing of last admin from the org/group

---

sdks/js/.changeset/metal-lemons-collect.md
sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/domain/verify-domain.tsx
sdks/js/packages/core/react/components/organization/members/index.tsx
sdks/js/packages/core/react/components/organization/members/invite.tsx
sdks/js/packages/core/react/components/organization/members/member.columns.tsx
sdks/js/pnpm-lock.yaml

Changes:
1. Show domain name instead of hardcoded placeholder.
2. Fix Table pagination
3. Add loader screen in add member modal. disable button if fields are not valid

fix: minor sdk issues

---

cmd/serve.go
config/sample.config.yaml
core/authenticate/config.go
docs/docs/reference/configurations.md

- the config is added under app.authentication.token.rsa_base64

feat: allow passing token RSA key as base64 config

---

internal/api/v1beta1/project.go

This PR will fix the issue of project update api setting the project title to empty string.

fix: update title in project update api

---

sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/onboarding/magiclink-verify.tsx
sdks/js/packages/core/react/components/onboarding/magiclink.tsx
sdks/js/packages/core/react/components/organization/domain/domain.columns.tsx
sdks/js/packages/core/react/components/organization/members/invite.tsx
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/components/organization/project/members/invite.tsx
sdks/js/packages/core/react/components/organization/project/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/sidebar/index.tsx
sdks/js/packages/core/react/components/organization/teams/members/index.tsx
sdks/js/packages/core/react/components/organization/teams/members/invite.tsx
sdks/js/packages/core/react/components/organization/teams/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/teams/team.tsx
sdks/js/packages/core/react/components/organization/teams/teams.columns.tsx
sdks/js/packages/core/utils/index.ts
sdks/js/pnpm-lock.yaml

1. Add roles filter to org and project member invite modal.
2. Add support for `enter` key in email login and otp form submit.
3. Add Headers to table columns
4. Add Group member invite modal, add support to add custom role while adding user
TODO: 
1. update select in apsara to handle large list.  https://github.com/raystack/apsara/pull/86 ✅ 
2. Create policy api for group not working https://github.com/raystack/frontier/pull/376 ✅

feat: add group member invite modal

---

cmd/serve.go
core/project/service.go
core/user/service.go
internal/bootstrap/schema/schema.go
internal/store/postgres/metaschemas/group.json
internal/store/postgres/metaschemas/org.json
internal/store/postgres/metaschemas/role.json
internal/store/postgres/metaschemas/user.json
test/e2e/regression/api_test.go
test/e2e/testbench/testdata/mocks/mock-organization.json

- currently listing group users returns all the users who have access to the group
- ideally it should only return users who were explicitly added as owner or member of the group
- same goes for listing project users

fix: group users listing should only have members

---

sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/create.tsx
sdks/js/packages/core/react/components/organization/members/invite.tsx
sdks/js/packages/core/react/components/organization/preferences/index.tsx
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/components/organization/project/add.tsx
sdks/js/packages/core/react/components/organization/project/delete.tsx
sdks/js/packages/core/react/components/organization/project/members/invite.tsx
sdks/js/packages/core/react/components/organization/project/project.tsx
sdks/js/packages/core/react/components/organization/project/projects.columns.tsx
sdks/js/packages/core/react/components/organization/teams/add.tsx
sdks/js/packages/core/react/components/organization/teams/index.tsx
sdks/js/packages/core/react/components/organization/teams/members/invite.tsx
sdks/js/packages/core/react/components/organization/teams/team.tsx
sdks/js/packages/core/react/hooks/useOrganizationTeams.ts
sdks/js/pnpm-lock.yaml

This PR will
1. remove the privacy column from project list as it is not used anywhere right now.
2. remove 180px width tailwind class from select components.
3. move useState inside the router to prevent creating new router everytime.
4. in project and team delete modal, the background page stills calls the get api after deletion due to location key change and throw 403 error.
5. Add option to switch between `current user joined teams` and `organization teams` for admin.

Fix(sdk): styling and rerendring issues

---

cmd/serve.go
core/group/group.go
core/user/service.go
internal/api/v1beta1/group.go
internal/api/v1beta1/group_test.go
internal/api/v1beta1/org.go
internal/api/v1beta1/org_test.go
internal/api/v1beta1/user.go
test/e2e/regression/api_test.go

- currently org to user relation ships are calculated dynamically and all direct or indirect access controls will be evaluated but after this change only users who are added as a member or given access via a policy will be listed. For example, super users will who have access to whole platform will not be part of the list if they don't have explicit access to the org.

fix: list only explicitly added org members

---

core/project/service.go

While looking for projects in policy repository, if there were no groups returned by group service, there were no filters applied on principal while querying policies returning projects which user has no direct relation

fix: listing projects with non-inherit roles handle no groups

---

README.md
go.mod
go.sum
main.go
pkg/server/server.go

- https://github.com/prometheus/client_golang provides better support for autogenerating dashboard with the provided metrics

feat: replace prometheus metric library

---

sdks/js/packages/core/client/V1Beta1.ts
sdks/js/packages/core/client/data-contracts.ts
sdks/js/packages/core/react/components/organization/project/index.tsx
sdks/js/packages/core/react/components/organization/project/projects.columns.tsx
sdks/js/packages/core/react/components/organization/teams/index.tsx
sdks/js/packages/core/react/components/organization/teams/teams.columns.tsx
sdks/js/packages/core/react/hooks/useOrganizationProjects.ts
sdks/js/packages/core/react/hooks/useOrganizationTeams.ts

This PR will change SDK to use `members_count` field from the group list and project list response to show the members count in the list tables.

refactor(sdk): use list apis member count field

---

billing/checkout/service.go
test/e2e/regression/billing_test.go

Success and Cancel urls can be templatized via `{{.CheckoutID}}`. 
For example: https://example.com/success?checkout_id={{.CheckoutID}}

feat: templatize checkout success/cancel url

---

billing/checkout/service.go

This PR will add `checkout_id` in the subscription's metadata after checkout

chore: add checkout_id to subscription metadata

---

.goreleaser.yml

This PR will update the goreleaser deprecated configs
1. brew `tap` is changed to `repository` https://goreleaser.com/deprecations/#brewstap
2. scoops `bucket` is changed to `repository` https://goreleaser.com/deprecations/#scoopsbucket
[
](url)

ci: remove goreleaser deprecated configs

---

ui/src/containers/users.list/index.tsx

By default, backend sends 50 users only if no pageSize is set.

fix (admin-ui): set default page size of 200 when fetching user list

---

internal/store/postgres/invitation_repository.go

Since the `user_id` field in the `invitations` table is of type text, it is prones to mismatches due to being case sensitive. This field usually takes the value of an email (can also take in any text we choose to pass), which are not case-sensitive in the real world. 
This PR removes the case-sensitivity of that field, and ensures that we store and fetch invitations in lowercase.
Pre-PR:
1. Invite `Abc@raystack.org` to an organization
2. User tries to login with Google or enters their email as `abc@raystack.org` -> we are unable to fetch any invitations
Post this PR:
1. Invite `Abc@raystack.org` to an organization
2. User tries to login with Google or enters their email as `abc@raystack.org` -> The invitation is shown

fix: prevent invitations from being case-sensitive

---

sdks/js/packages/core/react/components/organization/billing/invoices/index.tsx
sdks/js/packages/core/react/components/organization/plans/helpers/index.ts
sdks/js/packages/core/react/components/organization/plans/index.tsx

This PR will sort the features list in plans list screen.
the features which are available on more plans will be on top.
This PR will also fix the `Invalid Date` issue in invoice list component where no `effective_at` is available for `draft` invoice.

feat(sdk): sort plan features

---

billing/checkout/service.go
billing/config.go
billing/customer/service.go
billing/invoice/service.go
billing/product/service.go
billing/subscription/service.go
cmd/serve.go
config/sample.config.yaml
core/audit/context.go
core/audit/logger.go
core/audit/noop_repository.go
core/audit/service.go
core/deleter/deleter.go
core/deleter/service.go
core/event/listener.go
core/event/processor.go
core/event/publisher.go
internal/api/api.go
internal/store/blob/plan_repository.go
internal/store/blob/plans/sample.yaml
internal/store/postgres/audit_repository.go
internal/store/postgres/billing_customer_repository.go
internal/store/postgres/billing_invoice_repository.go
internal/store/postgres/billing_subscription_repository.go

- two additional configs are added to configure a default plan which should be free and will be subscribed automatically on org creation
- it creates a default billing account with most fields as empty except email. Org owner email is used as the default email of billing account.
- `billing.default_plan` and `billing.default_currency` needs to be set for it to apply

feat: subscribe to default plan on org creation

---

pkg/server/interceptors/authorization.go

Currently, some subscription management actions can be performed by users with delete permission on the org, whereas some others allow users with update permission to make subscription changes.
For example, currently, users with update permission can purchase a plan, but not change it (using ChangeSubscription API) or cancel it.
This PR tries to bring consistency to billing account and subscription management by allowing only users with org delete permission to manage both.
**Current:**
- Create Billing Account checks for `OrganizationUpdate` permission
- Update subscription checks for `OrganizationUpdate` permission
- Create checkout checks for `OrganizationUpdate` permission
- List checkouts checks for `OrganizationUpdate` permission
**Post this PR:**
- Create Billing Account checks for …

chore: billing account and subscription management should be done by users with org delete permission

---

config/sample.config.yaml
core/authenticate/config.go
core/authenticate/service.go
core/authenticate/strategy/mail_link.go
core/authenticate/strategy/mail_otp.go
core/authenticate/strategy/mail_otp_test.go
core/authenticate/test_users/config.go
core/domain/service.go
pkg/utils/domain.go

We are setting up automated end to end testing for our platform. 
The tests will create new users and new org for every test run.
but due to frontier login strategies it is very difficult to login from test user accounts.
We looked for multiple solution for this.
1. Use gmail apis to read inbox and get otp. eg [gmail-tester](https://github.com/levz0r/cypress-gmail-tester)
But this will expose real user gmail creds on CI.
2. Use throw away email to send otp in that and read email via api. eg [mailosour](https://mailosaur.com/email-testing)
3. Have support for test users and use hardcoded otp.
This PR will add support for test users. The test user is similar to [stripe payment test](https://docs.stripe.com/testing) where hardcoded payment methods can be used for testing.
The test users will …

feat: add test users login

---

docker-compose.yml

After adding values for the smtp settings in the docker-compose.yml file the login was still failing due to the mandatory TLS policy.
So including this additional smtp setting will allow new users to get up to speed faster.

Include all SMTP configuration option in the example docker-compose.yml

---

billing/customer/service.go

Without any default payment method:
With default payment method:

fix: send default payment method flag in metadata

---

internal/api/v1beta1/project.go
internal/api/v1beta1/project_test.go

This PR adds an error translator in projects handler which translates errors from services to response errors which are sent to users.
An additional change in this PR is an error type change:
In update project API for `organization.ErrInvalidUUID` the error being returned to user changes from `grpcProjectNotFoundErr` to `grpcBadBodyError` as it is a validation request associated with the request body. This change also makes it consistent with the create project API, which returns `grpcBadBodyError` as well in case of invalid UUIDs

chore: move project handler errors to common translator

---

core/audit/audit.go
core/group/service.go
core/webhook/service.go

We require a webhook which notifies downstream services about removal of user from groups. This PR introduces that into the service.
The reason for doing this in service is so that this event is triggered even if different handlers are used to perform this action.
The idea behind adding this instead of adding more and more information into policy events is to provide an easy to understand event to downstream services so that appropriate action can be taken by them. A few more events such as this will be introduced in subsequent PRs.

feat: emit audit event+webhook when user is removed from a group

---

.github/workflows/release.yml

We are using the `latest` version of goreleaser. However, a few days ago, goreleaser [v2](https://github.com/goreleaser/goreleaser/releases/tag/v2.0.0) was released, which has some breaking changes.
This PR will set the version of the goreleaser to v1. 
ref https://github.com/goreleaser/goreleaser-action/pull/461

ci: set goreleaser to v1

---

billing/customer/service.go
internal/store/postgres/billing_customer_repository.go
internal/store/postgres/billing_customer_repository_test.go
test/e2e/regression/billing_test.go

Billing account were not adding active state in db by default. We started adding active state later causing us to make the change backward compatible. This change while being made backward compatible used a where condition in db which although looked like it is using a `AND` between org and state filter, it was using an `OR`. The underlying library `goqu` didn't make it obvious to see from its methods.

fix: billing account with no state in db were failing entitlement checks

---

billing/product/product.go

- Product of seat limit behaviour can limit number of users allowed inside a plan via a config. It's default value was getting treated as explicit limit.

fix: product seat limit shouldn't use 0 as default

---

.golangci.yml
billing/credit/service.go
billing/subscription/service.go
config/sample.config.yaml
docs/docs/reference/configurations.md
internal/store/postgres/audit_repository.go
pkg/server/config.go
pkg/server/server.go

Mem/cpu/mutex profiles can be turned on for debug endpoint of metrics port via setting true on `app.profiler`.

feat: config to enable debug profilers

---

cmd/serve.go
cmd/server.go
pkg/server/server.go

Setting the metrics port under `app.metrics_port` as `0` disables the default endpoint and metrics collection for Prometheus.

fix: disable metrics endpoint if no port provided

---

billing/checkout/service.go
billing/config.go
billing/customer/service.go
billing/invoice/service.go
billing/subscription/service.go
billing/subscription/subscription.go
cmd/serve.go
config/sample.config.yaml
docs/docs/reference/configurations.md

Additional configurations are exposed to adjust refresh interval to sync with billing provider(stripe) based on services.
```
billing:
refresh_interval:
customer: 1m
subscription: 1m
invoice: 5m
checkout: 1m
```
Another change as part of checkout api is to cancel any running trials immediately if the user buy same plan.

feat: configure refresh interval to sync with billing provider

---

billing/plan/plan.go
billing/plan/service.go
internal/store/postgres/billing_plan_repository.go
test/e2e/regression/testdata/plans/subscription.credits.yaml

- Explicitly set `active` state, since otherwise it is set as empty string
- Return only active plans when listing plans, unless explicitly stated otherwise
This will help in using the `state` field in plans, to determine which plans to show/not show on the UI.
Plans table after these changes (earlier the state for all plans was ""):
```
frontier=# select name, state from billing_plans;
name              |  state   
--------------------------------+----------
monthly_enterprise_plan   | active
yearly_enterprise_plan    | active
standard_plan             | inactive
monthly_professional_plan | active
yearly_professional_plan  | active
(5 rows)
```
Output of list API call:
After the changes above, the list call returns only 4 plans from the DB shown above:
1. Monthly enterprise plan
2. …

fix: explicitly set state of plans as active so that it is not set as empty

---

billing/checkout/service.go
billing/subscription/service.go
billing/subscription/subscription.go

- Triling subscriptions were filtered out from the periodic syncer causing for it to stay in trialing state.
- Buying a trialing subscription will be canceled only after payment is finished

fix: trialing subscriptions failed to sync

---

ui/src/containers/organisations.list/billingaccounts/subscriptions/columns.tsx
ui/src/containers/organisations.list/billingaccounts/subscriptions/index.tsx
ui/src/contexts/App.tsx
ui/src/main.tsx
ui/src/utils/constants.ts
ui/src/utils/helper.ts

- Add status and cancellation columns in the subscription page.
- Add dayjs for formatting.
- Handle undefined planName. Fallback to '-'.
- Date filter type for start and end date.
- Typo fixes
Linear: [ID-505](https://linear.app/pixxel/issue/IDE-505/[admin-panel]-show-status-and-canceled-at-on-subscriptions-page)
URL: /organisations/`organisationId`/billingaccounts/`billingaccountId`/subscriptions
Testing:
Dev tested on Chrome.

feat(admin-ui): add cancellation and status

---

core/invitation/invite.go
core/invitation/service.go
internal/api/v1beta1/invitations.go
internal/api/v1beta1/invitations_test.go

IDE-499
fix: return error if user is tying to accept expired invite. Currently, user can accept expired 
API request:
`curl --location 'http://127.0.0.1:9080/v1beta1/organizations/<org_id>/invitations/<invite_id>/accept' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Cookie: sid= \
--data '{}'`
Response code
`400 Bad Request`
Response body:
`{"code":3,"message":"invitation expired","details":[]}`

fix: users are able to accept expired invitations

---

billing/invoice/service.go
internal/store/postgres/billing_invoice_repository.go

Few attributes in Stripe invoice are not populated instantly at the time of creation causing missing values persisted in db. These can be synced back later using periodic syncer.

fix: sync invoice attributes after it's created

---

core/event/service.go
internal/store/postgres/billing_subscription_repository.go

This PR solves a couple of issues:
1. We used to sync only the first subscription in our repository because the subscription repository did not use the providerID passed to it as input. This PR fixes that.
2. The event for "invoice created" cannot use the same provider id that is passed since the provider id there refers to invoice id, whereas the code written assumes that the id passed is a customer id. Due to issue (1), the "invoice created" event was anyway not getting triggered

fix: add filter for providerID on subscription repo, and remove unnecessary invoice event in syncer

---

billing/credit/service.go
billing/credit/service_test.go
internal/api/v1beta1/billing_usage.go
internal/store/postgres/billing_transactions_repository.go

When `CreateBillingUsage` API is called multiple times with same ID, it doesn't check if already debuted and tries to create transaction entry. This results in DB error `ERROR: duplicate key value violates unique constraint`,  HTTP status code  `500 `.
Applied a check to see if the ID is present. If no, it's BAU. If yes, it returns an error mentioning `credits already applied` with HTTP status code `409`.
1. Unique ID
Payload:
```
"usages": [
{
"id": "cbaef2b4-eb91-44c0-bdc4-eed02666ea70",
"customer_id": "",
"source": "",
"description": "",
"type": "credit",
"amount": "2",
"user_id": "",
"metadata": {},
"created_at": "",
"updated_at": ""
}
```
Response status:  `200 OK`
2. Duplicate ID
Payload:
```
"usages": [
{
"id": "cbaef2b4-eb91-44c0-bdc4-eed02666ea70",
"customer_id": "",
"source": …
```

fix: check if already deducted a transaction to avoid 5XX response.

---

ui/src/components/CustomField.tsx
ui/src/containers/organisations.list/serviceusers/columns.tsx
ui/src/containers/products.create/features-fields.tsx

fix: ts ci errors

---

billing/plan/service.go
cmd/serve.go
internal/store/postgres/billing_plan_repository.go

- Add prices to plan list API response
- Add plans array to product (for backward compatibility, since the earlier API contract used to return it)

fix: add prices to plan list response

---

sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/components/organization/sidebar/index.tsx
sdks/js/pnpm-lock.yaml

This PR will update the tanstack router in IAM SDK.
the `useRouterContext`  and `routerContext.createRootRoute` has been removed in this version.
the `routerContext.createRootRoute` is replaced with `createRootRouteWithContext`
and the `useRouterContext` is replaced with `useRouteContext`.
[link to router context ](https://tanstack.com/router/latest/docs/framework/react/guide/router-context)
[link to useRouteContext hook](https://tanstack.com/router/latest/docs/framework/react/api/router/useRouteContextHook)

feat(sdk): update tanstack router to 1.58.17

---

cmd/serve.go
config/sample.config.yaml
docs/docs/reference/configurations.md
internal/store/spicedb/config.go
internal/store/spicedb/relation_repository.go
test/e2e/regression/api_test.go

Config has additional flag to debug permission checks which can be enabled via `spicedb.check_trace:true`

test: spicedb tracer to debug check calls

---

internal/api/v1beta1/permission_check.go

Problem.
If a random ID is passed in the `CheckFederatedResourcePermission` API `resource` body. The API throws an `Internal` error. And in the server logs, the error is `resource doesn't exist`. 
After debugging, I found that we [fetch the resource from the db](https://github.com/raystack/frontier/blob/main/core/resource/service.go#L222), and it returns `ErrNotExist` error.
This error was not handled in the API handler function.
This PR adds a check for the `resource.ErrNotExist` error. It also refactors the switch statement.

fix: check for resource.ErrNotExist error in check permission

---

core/role/service.go
internal/api/v1beta1/billing_checkout.go
internal/api/v1beta1/billing_customer.go
internal/api/v1beta1/deleter.go
internal/store/postgres/relation_repository.go
internal/store/postgres/relation_repository_test.go
internal/store/postgres/user_repository.go

Currently while updating role, frontier used to identify the deleted permissions from role and only remove them which are needed. One problem with this is if in case someone manually modifies such roles and the permissions gets out of sync, it will not try to correct them. Now it deletes all existing permissions and create the new requested on every update call.

fix: while updating role, do full refresh of permissions

---

internal/api/v1beta1/org.go
internal/api/v1beta1/org_test.go
internal/store/postgres/billing_transactions_repository.go
internal/store/postgres/group_repository.go
internal/store/postgres/organization_repository.go
test/e2e/regression/billing_test.go
test/e2e/testbench/testbench.go

Currently there were chances to have race conditions while writing to transaction repository. I have added a test to verify it doesn't happen. Database is using `Serializable` as the isolation level to avoid overlapping transactions.

fix: add isolation level in transaction repository

---

core/policy/filter.go
internal/api/v1beta1/org.go
internal/store/postgres/policy_repository.go
test/e2e/regression/api_test.go

- https://github.com/raystack/proton/pull/371
- a list of role name/ids are accepted as inputs, it can't be used when `with_roles` is toggled on.

feat: role filter while listing organization users

---

billing/config.go
billing/subscription/service.go
config/sample.config.yaml

This PR will update the `end_behavior` in the cancel upcoming phase 
If the user is on trial and config.subscription.cancel_after_trial is set to true, then the `end_behavior` in [subscription update call ](https://docs.stripe.com/api/subscription_schedules/object#subscription_schedule_object-end_behavior)will be set to `cancel`

feat: cancel subscription after trial

---

sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/onboarding/magiclink.tsx
sdks/js/pnpm-lock.yaml

This PR will update validation for the email field in the signup and login form.
Some [issue](https://github.com/jquense/yup/issues/507) with `yup` for checking email.
Thus, the `validator` package is used to validate emails.

feat(sdk): add email validation

---

sdks/js/packages/core/react/components/organization/project/members/index.tsx
sdks/js/packages/core/react/components/organization/project/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/project/members/remove.tsx
sdks/js/packages/core/react/components/organization/project/project.tsx
sdks/js/packages/core/react/components/organization/routes.tsx

This PR will add functionality to remove a member from a project.
a member can be an individual user or a team.
a dialog box will open for confirmation when the user clicks on the remove options.
once the user confirms the member removal, all policies for that member and project will be deleted.
This PR also adds support for search users via email in the invite flow.

feat(sdk): add dialog to remove member from project

---

billing/checkout/service.go
billing/customer/service.go
billing/invoice/service.go
billing/subscription/service.go

This will help us to run a single pod that does the background sync, while other pods can just serve http requests.

feat: add a way to disable background sync jobs

---

core/authenticate/service.go
core/organization/service.go
internal/metrics/metrics.go
internal/metrics/service.go
internal/store/postgres/organization_repository.go
internal/store/postgres/organization_repository_test.go
internal/store/postgres/project_repository.go
internal/store/postgres/project_repository_test.go

All org and project slugs will be converted to lower case before they are created. Existing org and projects will continue to work as usual.
- Added additional metrics latency for authenticate GetPrincipal and organization ListByUser methods.

fix: make org and project name case insensitive

---

core/webhook/service.go
pkg/server/consts/gateway.go
pkg/server/interceptors/authorization.go
pkg/server/interceptors/enrich.go
pkg/server/server.go
test/e2e/regression/api_test.go

Header with name "X-Request-Id" if available in request headers will be added as field in frontier logs.

feat: add request id header if available to application log

---

internal/api/v1beta1/authenticate.go
internal/bootstrap/service.go
internal/store/postgres/flow_repository.go

This PR adds the following changes.
1. Return `BadRequest` for invalid flow otp error.
2. Return `BadRequest` instead of `Internal` if the flow data is not in the table.
3. Trim user emails in the superuser bootstrap function.

fix: invalid otp internal error

---

internal/api/v1beta1/authenticate.go

This PR fix the `Internal` status code for context cancelled error in AuthToken.
Once the client cancels the request, we get context canceled in our code.
we should return the `Canceled` status code for this request. But here we are returning an `Internal` error.
we already have an [interceptor](https://github.com/raystack/frontier/blob/main/pkg/server/interceptors/errors.go#L30), which checks the following.
1. if the error is context canceled, then return `Canceled` status.
2. If the error is already a grpc error, then return as it is.
3. return everything else as an `Internal` error.
The problem is that the `AuthToken` handler already wraps the error grpc error with the status `Internal`. Thus, the interceptor is ignoring it.
This PR removes that wrapper and lets the interceptor handle …

fix: handle context canceled error in AuthToken handler

---

billing/invoice/service.go

This PR will fix the issue when the upcoming invoice API is called for a customer who is on no-plan and doesn't have an account created in Stripe.
For that customer, the provider ID is empty.
We should return an empty invoice object to them instead of an error.

fix: dont call stripe upcoming invoice if provider id not available

---

internal/store/postgres/org_users_repository.go

**Add datetime operator support for OrgUsersRepository filters**
Changes:
- Extended operator validation in buildNonRoleFilterCondition to support datetime operators
- Added support for comparison operators (gt, lt, gte, lte) for datetime fields
- Maintained existing string operator support while clearly separating operator types

fix: add check for datetime operators in Org User Search API

---

core/audit/audit.go
internal/api/v1beta1/billing_customer.go
internal/api/v1beta1/billing_customer_test.go
internal/api/v1beta1/kyc.go
internal/api/v1beta1/kyc_test.go
pkg/server/interceptors/authorization.go

This pull request introduces new audit logging functionality for billing account updates and organization KYC updates, along with corresponding test cases and authorization enhancements. The most significant changes include the addition of audit events, integration of these events into existing handlers, and updates to tests and authorization logic to support the new functionality.
* Added `OrgKycUpdatedEvent` and `BillingAccountDetailsUpdatedEvent` to the `EventName` constants in `core/audit/audit.go` to support logging for organization KYC updates and billing account detail updates. [[1]](diffhunk://#diff-0bf1f762614bb3cb4dfa09ae2cc80f4125c305b90f3bdc3f2a5dca61d5e2db76R83) [[2]](diffhunk://#diff-0bf1f762614bb3cb4dfa09ae2cc80f4125c305b90f3bdc3f2a5dca61d5e2db76R92-R93)
* Integrated audit …

feat: add audit logs for billing account details update and kyc update

---

internal/store/postgres/user_repository.go
internal/store/postgres/user_repository_test.go

- Make user search filter case insensitive by using postgres ilike/notilike operators                                                                                                                        
- Improves UX by allowing case-insensitive text matching when filtering users                                                                                                                                  
- Test user search with mixed case input matches users regardless of case                                                                                                                                      
- Verify notlike operator also works case-insensitively …

fix: make like and notlike case insensitive in User Search API

---

sdks/js/packages/core/react/components/organization/sidebar/index.tsx

fix (Sidebar): Resize handle visible even though Sidebar is not collapsible
fix (Sidebar): Sidebar Search top margin
refactor (Sidebar): Replace Inputfield with Search and add clear button
**Note: Merge this PR after [PR-428](https://github.com/raystack/apsara/pull/428) is merged and released.**

fix (sidebar): resize handle visible when collapse/expand is disabled

---

sdks/js/packages/core/api-client/V1Beta1.ts
sdks/js/packages/core/api-client/WellKnown.ts
sdks/js/packages/core/api-client/data-contracts.ts
sdks/js/packages/core/api-client/http-client.ts
sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/tokens/index.tsx
sdks/js/packages/core/react/components/organization/tokens/token.module.css
sdks/js/packages/core/react/contexts/FrontierContext.tsx
sdks/js/packages/core/scripts/gen-swagger-client.mjs

This pull request introduces a banner to inform overdraft users, i.e. users with credit_min set to negative, of the behaviour of how adding tokens and paying invoices works.

feat: add banner for postpaid users

---

pkg/server/server.go
ui/package-lock.json
ui/package.json
ui/src/components/Sidebar/index.tsx
ui/src/components/states/Unauthorized.tsx
ui/src/contexts/ConnectProvider.tsx
ui/src/main.tsx
ui/src/pages/organizations/details/index.tsx
ui/vite.config.ts

This PR sets up the RPC for the admin UI.
This is making 2 major changes.
In UI, we are adding connect-query and the raytack proton package.
We are updating the GetOrganization and AuthLogout API to use connect RPC calls.
The admin UI will need 2 endpoints to connect to the backend. 
- one for REST server
- another one for Connect Server.
Vite will proxy both API while developing locally.
We are adding 1 more proxy in serveUI. This will proxy all the calls coming from the admin UI to the connect port.

feat: setup connect rpc for admin ui

---

sdks/js/packages/core/react/hooks/useTokens.ts

This PR fixes the issue of calling get token balance with a different org and billing account ID.
As the useEffect dependencies are keys from 2 different objects, they may not be in sync in some cases, which can result in a 403 error.

fix(sdk): keep billing account and org id in sync

---

sdks/js/packages/core/hooks/index.ts
sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/onboarding/magiclink-verify.tsx
sdks/js/packages/core/react/components/onboarding/magiclink.tsx
sdks/js/packages/core/react/components/onboarding/signin.tsx
sdks/js/packages/core/react/components/onboarding/signup.tsx
sdks/js/packages/core/react/components/organization/routes.tsx
sdks/js/packages/core/react/contexts/FrontierContext.tsx
sdks/js/packages/core/react/contexts/FrontierProvider.tsx
sdks/js/packages/core/shared/types.ts
sdks/js/packages/core/tsconfig.json
sdks/js/packages/core/tsup.config.ts
sdks/js/packages/sdk-demo/src/pages/Callback.tsx
sdks/js/packages/sdk-demo/src/pages/Home.tsx
sdks/js/packages/sdk-demo/vite.config.ts
sdks/js/pnpm-lock.yaml

This PR sets up the connect-rpc client with [connect-query](https://github.com/connectrpc/connect-query-es) (wrapper of react-query).
The method definitions are coming from the `@raystack/proton/frontier` package.
The  `@raystack/proton/frontier` package is TypeScript code generated from the https://github.com/raystack/proton repo.
Following methods are migrated to connect-rpc method instead of fetch calls.
1. ListAuthStrategies
2. Authenticate
3. AuthCallback
4. GetOrganization
5. AuthLogout
This PR also added `/hooks` entry path in `@raystack/frontier`, which exports the connect-query hooks and frontier service methods, so the consumer apps don't need to install `@raystack/proton` and `@connectrpc/connect-query` packages and just use the export from `@raystack/frontier/hooks`
The SDK …

feat(sdk): setup connect query and migrate authn calls

---

sdks/js/packages/core/react/components/organization/tokens/add-tokens.tsx

This pull request makes a small update to the validation logic for adding tokens in the `AddTokens` component. The main change is to provide more specific and user-friendly error messages for invalid token inputs.
- Improved error messaging for invalid token input in the `AddTokens` form, ensuring users see clearer instructions when entering an incorrect value.

fix(sdk): validation message when number of tokens to be added is left empty

---

sdks/js/packages/core/react/components/organization/project/index.tsx
sdks/js/packages/core/react/components/organization/teams/index.tsx

This pull request makes a minor update to the search placeholders in the organization projects and teams tables, improving clarity by changing "Search by name" to "Search by title".
- UI Text Consistency:
* Updated the `DataTable.Search` placeholder in `ProjectsTable` to "Search by title" for clearer intent. (`sdks/js/packages/core/react/components/organization/project/index.tsx`)
* Updated the `DataTable.Search` placeholder in `TeamsTable` to "Search by title" for consistency with the projects table. (`sdks/js/packages/core/react/components/organization/teams/index.tsx`)

fix(sdk): update search bar placeholders to match the table column name

---

sdks/js/packages/core/react/contexts/FrontierProvider.tsx

This PR adds a custom fetch to transport in connect-query.
Custom fetch is needed to pass credentials in the api calls as mentioned [here](https://github.com/connectrpc/connect-es/blob/main/packages/connect-web/src/connect-transport.ts#L110)

fix(sdk): pass credentials to connect query fetch

---

internal/api/v1beta1/authenticate.go
internal/api/v1beta1/authenticate_test.go
internal/api/v1beta1connect/authenticate.go
internal/api/v1beta1connect/authenticate_test.go

This PR adds a check for disabled org in AuthToken Calls for service users.
A normal user can exist without any org, and their token can have no org IDs.
But a service user belongs to only one organization, and if an organization is disabled, then all auth token calls for its service users should fail.

fix: add check for disable org for service users in AuthToken Calls.

---

ui/src/pages/users/list/navbar.tsx

This PR migrates the Admin exportUsers api to the connect-rpc call.
The new download method uses `content-type: application/connect+proto` and download the file from binary stream

feat(admin-ui): migrate export users to connect rpc

---

billing/credit/credit.go
billing/usage/service.go
internal/store/postgres/billing_transactions_repository.go

This approach does not use any locks/transactions, instead relies on creating a chain of revert transactions for the original transaction.

feat: support multiple reverts on same transaction

---

sdks/js/packages/core/react/components/organization/user/update.tsx

- Added early return check in onSubmit to prevent duplicate form submissions
- Synchronized submit logic with button disabled state (isLoading || isSubmitting)
- Fixes duplicate success notifications when rapidly clicking submit button

fix: prevent duplicate submissions on user profile update

---

internal/api/v1beta1connect/webhook.go

The following RPCs are migrated. 
The implementation of the handlers is similar to that of the gRPC handlers. 
I have just made it compatible with the ConnectRPC signature. 
We have used connect errors instead of gRPC errors.

feat: migrate Admin Webhook APIs to connectRPC server

---

ui/src/pages/organizations/details/contexts/organization-context.tsx
ui/src/pages/organizations/details/edit/organization.tsx
ui/src/pages/organizations/details/index.tsx
ui/src/pages/organizations/details/layout/index.tsx
ui/src/pages/organizations/details/layout/navbar.tsx
ui/src/pages/organizations/details/side-panel/index.tsx
ui/src/pages/organizations/details/side-panel/org-details-section.tsx
ui/src/pages/organizations/details/types.ts
ui/src/pages/organizations/list/columns.tsx
ui/src/pages/organizations/list/index.tsx

This PR updates the `V1Beta1Organization` type to the `Organization` type from proton.
We have already migrated the `getOrganization` api to connect RPC, which gives `Organization` as the response.
But in component props, we were using `V1Beta1Organization` as a type, which we used to get from the REST API.
The fields were snake_case in the REST response and in camelCase in the Connect TS client. 
Thus, we get an undefined value when we use multi-word keys like `createdAt`.
This PR fixes that issue.

fix(admin-ui): replace V1Beta1Organization to proton OrganizationSchema

---

internal/api/v1beta1connect/platform.go
internal/api/v1beta1connect/preferences.go

The following RPCs are migrated. 
The implementation of the handlers is similar to that of the gRPC handlers. 
I have just made it compatible with the ConnectRPC signature. 
We have used connect errors instead of gRPC errors.

feat: migrate admin Preferences and Platform APIs to Connect RPC

---

Makefile
core/auditrecord/mocks/repository.go
core/auditrecord/service.go
internal/api/v1beta1connect/audit_record.go
internal/api/v1beta1connect/mocks/audit_record_service.go
internal/store/postgres/audit_record_repository.go
internal/store/postgres/audit_record_repository_test.go
pkg/server/connect_interceptors/authorization.go
pkg/utils/rql.go
proto/apidocs.swagger.yaml
proto/v1beta1/admin.pb.go
proto/v1beta1/admin.pb.validate.go
proto/v1beta1/admin_grpc.pb.go
proto/v1beta1/frontierv1beta1connect/admin.connect.go
proto/v1beta1/models.pb.go
proto/v1beta1/models.pb.validate.go

This PR implements the ExportAuditRecords RPC for streaming audit record data as CSV files.
Implementation Details
- Repository Layer: Uses PostgreSQL server-side cursors to handle large datasets without loading all records into memory. Fetches data in configurable batches (1000 records) and streams via io.Pipe to the handler.
- Handler Layer: Receives the data stream from repository and forwards it to the client using Connect's server-side streaming with chunked HTTP responses (200KB chunks).
- RQL Support: Supports filtering, searching, and sorting through RQL query parameters, consistent with the existing ListAuditRecords endpoint.
- Memory Efficiency: The cursor-based approach ensures constant memory usage regardless of result set size, making it suitable for exporting large number of …

feat: Implement export audit records rpc with streaming

---

internal/api/v1beta1connect/errors.go
internal/api/v1beta1connect/metaschema.go
internal/api/v1beta1connect/permission_check.go
internal/api/v1beta1connect/user.go
internal/api/v1beta1connect/user_test.go
pkg/server/connect_interceptors/authentication.go

Migrate User API handlers from gRPC to Connect RPC
- Updated function signatures to use `connect.Request[T]` and `connect.Response[T]`
- Modified request field access to use `request.Msg.GetFieldName()`
- Converted error handling to Connect RPC error codes
- Added comprehensive tests for migrated functionality
- Preserved logger functionality with `grpczap.Extract(ctx)`
**🎉 COMPLETED: 21/21 APIs (100%) - MIGRATION COMPLETE! 🎉**
- `internal/api/v1beta1connect/user.go` - Added comprehensive API migrations including ListProjectsByCurrentUser
- `internal/api/v1beta1connect/user_test.go` - Added comprehensive tests for all migrated APIs  
- `internal/api/v1beta1connect/permission_check.go` - Added fetchAccessPairsOnResource helper method
- `internal/api/v1beta1connect/metaschema.go` - Added …

feat: migrate User APIs to Connect RPC

---

internal/api/v1beta1connect/project.go
internal/api/v1beta1connect/project_test.go

The following RPCs are migrated. 
The implementation of the handlers is similar to that of the gRPC handlers. 
I have just made it compatible with the ConnectRPC signature. 
We have used connect errors instead of gRPC errors.

feat: migrate Project APIs to connectRPC server

---

internal/api/v1beta1connect/errors.go
internal/api/v1beta1connect/group.go
internal/api/v1beta1connect/group_test.go
internal/api/v1beta1connect/metaschema.go

✅ **COMPLETE**: Successfully migrated all Groups APIs from gRPC to Connect RPC format as part of the IAM API standardization initiative.
- **100% API Coverage**: All 11 Groups APIs successfully migrated
- **Comprehensive Testing**: 50+ test cases covering all error scenarios and success flows
- **Zero Breaking Changes**: All original business logic preserved with identical functionality
- **Modern Interface**: Enhanced type safety and improved tooling support with Connect RPC
- **Quality Assurance**: All builds, tests, and lints pass successfully
- **Systematic Approach**: Established repeatable migration methodology
- Migrated handler signatures to use Connect RPC request/response wrappers
- Updated error handling to use Connect error codes and constants
- Preserved all business logic …

feat: migrate frontier Groups APIs to Connect RPC

---

internal/api/v1beta1connect/errors.go
internal/api/v1beta1connect/resource.go
internal/api/v1beta1connect/resource_test.go

This PR migrates all Resource management APIs from gRPC to Connect RPC framework, following the established patterns from previous API migrations.
Converting Resource APIs from traditional gRPC handlers to buf Connect RPC handlers with proper error handling, request/response wrapping, and comprehensive test coverage.
| API | Status | Commit | Implementation | Tests |
|-----|--------|--------|---------------|-------|
| `ListResources` | ✅ Complete | 2cc8b7c | `internal/api/v1beta1connect/resource.go:18-41` | 3 test cases |
| `ListProjectResources` | ✅ Complete | ebc4f77 | `internal/api/v1beta1connect/resource.go:43-64` | 4 test cases |
| `CreateProjectResource` | ✅ Complete | 232c72d | `internal/api/v1beta1connect/resource.go:66-125` | 7 test cases |
| `GetProjectResource` | ✅ Complete | …

feat: migrate Resource APIs to Connect RPC

---

internal/api/v1beta1connect/errors.go
internal/api/v1beta1connect/preferences.go
internal/api/v1beta1connect/preferences_test.go

This PR migrates Preferences management APIs from gRPC to Connect RPC framework, following the established patterns from previous API migrations.
Converting Preferences APIs from traditional gRPC handlers to buf Connect RPC handlers with proper error handling, request/response wrapping, and comprehensive test coverage.
| API | Status | Commit | Implementation | Tests |
|-----|--------|--------|---------------|-------|
| `DescribePreferences` | ✅ Complete | 0f38720 | `internal/api/v1beta1connect/preferences.go:155-164` | 3 test cases |
| `CreateOrganizationPreferences` | ✅ Complete | 3821b31 | `internal/api/v1beta1connect/preferences.go:60-86` | 4 test cases |
| `ListOrganizationPreferences` | ✅ Complete | 8bc0396 | `internal/api/v1beta1connect/preferences.go:91-106` | 4 test cases |
| …

feat: migrate Preferences APIs to Connect RPC

---

internal/api/v1beta1connect/namespace.go
internal/api/v1beta1connect/namespace_test.go
internal/api/v1beta1connect/permission.go
internal/api/v1beta1connect/permission_check.go
internal/api/v1beta1connect/permission_check_test.go
internal/api/v1beta1connect/permission_test.go
internal/api/v1beta1connect/relation.go
internal/api/v1beta1connect/relation_test.go

The following RPCs are migrated. 
The implementation of the handlers is similar to that of the gRPC handlers. 
I have just made it compatible with the ConnectRPC signature. 
We have used connect errors instead of gRPC errors.
**One crucial change** made is that the following APIs have been put behind an Authentication check, which was not implemented in the GPRC handler. 
The reason is that these APIs store Frontier resource-level permission names. They should at least be checked for authentication.

feat: migrate relations, permissions and namespaces RPC to ConnectRPC

---

internal/api/v1beta1connect/authenticate.go
internal/api/v1beta1connect/authenticate_test.go
internal/api/v1beta1connect/errors.go
internal/api/v1beta1connect/session.go

This PR migrates the Session APIs from gRPC to Connect RPC following Linear ticket CLD-2269.
- **GetJWKs API**: Successfully migrated from gRPC to Connect RPC format
- Added `GetJWKs` handler to `authenticate.go` with proper error handling
- Reused existing `toJSONWebKey` helper function from `serviceuser.go`
- Created comprehensive test suite covering success and edge cases
- All tests pass with proper protogetter lint compliance
- **Session APIs Error Handling**: Improved all existing session APIs with consistent Connect RPC patterns
- Replaced raw error propagation with proper Connect RPC error constants
- Added new error constants: `ErrSessionNotFound`, `ErrInvalidSessionID`, `ErrInvalidUserID`
- Applied consistent error handling across all 5 session endpoints
- Removed unused imports …

feat: migrate Session APIs to Connect RPC

---

internal/api/v1beta1connect/audit.go
internal/api/v1beta1connect/audit_test.go

This PR migrates the Organization Audit Logs APIs from gRPC to Connect RPC following Linear ticket CLD-2271.
- **ListOrganizationAuditLogs**: Successfully migrated from gRPC to Connect RPC format
- Added proper organization validation and error handling
- Implemented audit filter support for source, action, time range, and system filtering
- Transform audit logs to protobuf format with proper timestamp handling
- **CreateOrganizationAuditLogs**: Migrated with comprehensive validation
- Organization existence and status validation
- Required field validation (source and action)
- Batch processing of multiple audit logs in single request
- Proper actor, target, and context mapping
- **GetOrganizationAuditLog**: Single audit log retrieval with organization checks
- Organization validation …

feat: migrate Audit Logs APIs to Connect RPC
