src/plugin/logging.ts

fix: logs for http request

---

api/handler/v1/group.go
api/handler/v1/v1.go
cmd/serve_api.go
go.mod
go.sum
internal/group/groups.go
model/model.go
store/postgres/groups.go
store/postgres/migrations/20211101193307_create_groups_table.down.sql
store/postgres/migrations/20211101193307_create_groups_table.up.sql

feat: group api

---

api/handler/v1/role.go
api/handler/v1/v1.go
go.mod
go.sum
internal/roles/roles.go
model/model.go
store/postgres/migrations/20211115162818_create_roles_table.down.sql
store/postgres/migrations/20211115162818_create_roles_table.up.sql
store/postgres/migrations/roles.go
store/postgres/roles.go

feat: role api

---

.gitignore
api/handler/v1/project_test.go
api/handler/v1/user.go
api/handler/v1/user_test.go
api/handler/v1/v1.go
cmd/serve_api.go
config/config.go
go.mod
go.sum
internal/user/user.go
store/postgres/user.go

feat: add get/update self user apis

---

.gitignore
.shield.sample.yaml
cmd/serve_proxy.go
config/config.go
resources_config/resources.yaml
store/blob/resources_repository.go
structs/resources.go

File example:
```yaml
---
- name: dagger
actions:
- read:
- team_admin
- dagger_manager
- org_admin
delete:
- team_admin
- org_admin
- name: firehose
actions:
- read:
- team_admin
- firehose_manager
delete:
- team_admin
- org_admin
```

feat: reading resources file

---

hook/authz/authz.go
hook/hooks.go
integration/fixtures/ruleset.rest.yaml
middleware/authz/authz.go
pkg/body_extractor/json_payload.go
store/blob/rule_repository.go
structs/rule.go

feat: use namespace from rule config

---

cmd/serve.go
hook/authz/authz.go
internal/bootstrap/bootstrap.go
internal/permission/relation.go
resources_config/resources.yaml
store/blob/resources_repository.go

qa/fix: hooks to create resource for owner role

---

api/handler/v1beta1/action.go
api/handler/v1beta1/namespace.go
api/handler/v1beta1/project.go
cmd/action.go
cmd/client.go
cmd/cmd.go
cmd/group.go
cmd/namespace.go
cmd/organization.go
cmd/policy.go
cmd/project.go
cmd/role.go
cmd/user.go
cmd/utils.go
go.mod
go.sum
internal/schema/action.go
internal/schema/namespace.go
internal/schema/schema.go
store/postgres/action.go
store/postgres/groups.go
store/postgres/namespace.go
store/postgres/projects.go
store/postgres/resource.go

feat: shield commands for all APIs

---

cmd/setup.go
config/config.go
hook/authz/authz.go
hook/authz/authz_test.go
hook/hooks.go
middleware/authz/authz.go
middleware/middleware.go
pkg/sql/sql.go
resources_config/resources.yaml
store/blob/resources_repository.go
store/postgres/resource.go
utils/permission.go

```
if resource_name="*":
id := "p/{PROJECT_ID}/{NAMESPACE}"
else:
id := "r/{NAMESPACE}/{resource_name}"
```

Resource config reformat with no res changes

---

api/handler/v1beta1/project.go
api/handler/v1beta1/project_test.go
internal/permission/relation.go
internal/project/project.go
store/postgres/projects.go

feat(project): project admin APIs

---

cmd/serve_proxy.go
config/config.go
middleware/authz/authz.go

add header for user id

---

internal/permission/check.go
utils/permission.go

skip check database resource call for system namespaces

fix: check permission

---

core/role/role.go
docker-compose.yml

fix: error in bootstrapping role table from fresh db

---

core/resource/service.go
internal/store/postgres/action_repository.go
internal/store/postgres/role_repository.go

- Re-add `DefaultStringIfEmpty` function and continue to clean this up in another [issue](https://github.com/odpf/shield/issues/136)

fix: revert DefaultStringIfEmpty function usage

---

.shield.yaml
core/bootstrap/bootstrap.go
core/namespace/namespace.go
core/resource/resource.go
core/resource/service.go
internal/proxy/middleware/authz/authz.go
internal/store/blob/resources_repository.go
internal/store/postgres/migrations/20220802035409_add_backend_and_resource_type_column_in_namespace.down.sql
internal/store/postgres/migrations/20220802035409_add_backend_and_resource_type_column_in_namespace.up.sql
internal/store/postgres/namespace.go
internal/store/postgres/namespace_repository.go
internal/store/postgres/namespace_repository_test.go
internal/store/postgres/resource_repository.go
internal/store/postgres/resource_repository_test.go
internal/store/postgres/testdata/mock-namespace.json

feat: get resource from store using backend and resource type instead of urn

---

core/policy/policy.go
core/resource/resource.go
core/resource/service.go
internal/api/v1beta1/resource.go
internal/api/v1beta1/resource_test.go
internal/proxy/hook/authz/authz.go
internal/proxy/hook/authz/authz_test.go
internal/proxy/middleware/authz/authz.go
internal/store/postgres/policy.go
internal/store/postgres/policy_repository.go
internal/store/postgres/policy_repository_test.go
internal/store/postgres/postgres_test.go
internal/store/postgres/resource.go
internal/store/postgres/resource_repository.go
internal/store/postgres/resource_repository_test.go

feat: schema migration & revision in ShieldDB for resources

---

internal/store/postgres/group_repository.go

fix: bug in query for list group relations

---

Makefile
core/group/group.go
internal/api/v1beta1/errors.go
internal/api/v1beta1/permission_check_test.go
internal/api/v1beta1/relation.go
internal/api/v1beta1/relation_test.go
internal/proxy/hook/authz/authz_test.go
internal/store/postgres/group_repository.go
internal/store/postgres/group_repository_test.go
internal/store/postgres/namespace_repository_test.go
internal/store/postgres/policy_repository_test.go
internal/store/postgres/role_repository.go
internal/store/postgres/role_repository_test.go
internal/store/postgres/user_repository_test.go

Increasing test coverage with a target of 75% from 51%.

test: increase test coverage

---

cmd/serve.go
core/resource/service.go
internal/proxy/hook/authz/authz.go
internal/proxy/hook/authz/authz_test.go
test/e2e_test/smoke/proxy_test.go
test/e2e_test/testbench/testbench.go

Feature to use either slug or project id in hooks

feat: use project slug in hooks 

---

cmd/serve.go
core/authenticate/registration_flow.go
core/authenticate/session/service.go
internal/api/v1beta1/authenticate.go
internal/api/v1beta1/mocks/registration_service.go
internal/api/v1beta1/mocks/session_service.go
internal/store/memory/session_repository.go
internal/store/postgres/flow_repository.go
internal/store/postgres/session_repository.go
test/e2e_test/testbench/testbench.go

feat: add a cron job to remove expired sessions from database 

---

sdks/react/.gitignore
sdks/react/package-lock.json
sdks/react/package.json
sdks/react/rollup.config.js
sdks/react/src/contexts/ShieldContext.tsx
sdks/react/src/contexts/ShieldProvider.tsx
sdks/react/src/contexts/StrategyContext.tsx
sdks/react/src/contexts/UserContext.tsx
sdks/react/src/contexts/useMaxAllowedInstancesGuard.tsx
sdks/react/src/index.ts
sdks/react/src/shield.tsx
sdks/react/src/types/base.ts
sdks/react/src/types/index.ts
sdks/react/src/types/provider.ts
sdks/react/src/types/shield.ts
sdks/react/src/types/user.ts
sdks/react/tsconfig.json

feat: react sdk for shield

---

sdks/js/packages/core/react/components/onboarding/magiclink.tsx
sdks/js/packages/core/react/components/onboarding/signin.tsx
sdks/js/packages/core/react/components/onboarding/signup.tsx
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/contexts/FrontierContext.tsx
sdks/js/packages/core/shared/types.ts

add support for callback url after signin/signup
pass default route to OrganizationProfile Component

Chore: add callback url support

---

.github/workflows/main.yml
docs/docs/authn/serviceuser.md
internal/api/v1beta1/authenticate.go
pkg/server/consts/gateway.go
pkg/server/server.go

- Using header x-project in the token request, if the principal has access, it will be added as a claim

feat: custom claim of project id in jwt token

---

sdks/js/.changeset/calm-zebras-shave.md
sdks/js/packages/core/client/V1Beta1.ts
sdks/js/packages/core/client/data-contracts.ts
sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/project/members/index.tsx
sdks/js/packages/core/react/components/organization/project/projects.columns.tsx
sdks/js/packages/core/react/components/organization/teams/teams.columns.tsx
sdks/js/pnpm-lock.yaml

Changes:
1. Add headers to the project table
2. Show Title in projects and team table
3. Add Project update permission check in project `Add Team` button

Fix: show sdk table title column

---

core/user/service.go
internal/api/v1beta1/group_test.go
internal/store/postgres/role_repository.go
internal/store/postgres/role_repository_test.go
test/e2e/regression/api_test.go

- org user list excludes super users now

fix: make role scope list filter work as AND

---

cmd/serve.go
core/deleter/service.go
core/group/service.go
core/organization/service.go
internal/store/spicedb/relation_repository.go
pkg/server/interceptors/authorization.go

- after deletion, user was still part of org
- disabled create relation to avoid misuse of API

fix: delete user from an org

---

sdks/js/packages/core/react/components/organization/domain/add-domain.tsx
sdks/js/packages/core/react/components/organization/domain/delete.tsx
sdks/js/packages/core/react/components/organization/domain/domain.columns.tsx
sdks/js/packages/core/react/components/organization/general/general.module.css
sdks/js/packages/core/react/components/organization/general/general.profile.tsx
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/components/organization/project/delete.tsx
sdks/js/packages/core/react/components/organization/project/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/sidebar/helpers.ts
sdks/js/packages/core/react/components/organization/teams/delete.tsx
sdks/js/packages/core/react/components/organization/teams/members/invite.tsx
sdks/js/packages/core/react/components/organization/teams/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/user/avatar.tsx
sdks/js/packages/core/react/components/organization/user/update.tsx

This PR will add following changes
1. remove preference link for sidebar as it is not working properly.
2. Add domain validation in add domain
3. Add confirmation for domain delete
4. fix delete team modal close button link
5. remove hardcoded names from delete team and delete project page.
6. Show `Member` instead of `userIds` in invite member error message

fix(sdk): add domain validation

---

sdks/js/packages/core/client/V1Beta1.ts
sdks/js/packages/core/client/data-contracts.ts
sdks/js/packages/core/package.json
sdks/js/packages/core/react/components/organization/domain/domain.columns.tsx
sdks/js/packages/core/react/components/organization/members/index.tsx
sdks/js/packages/core/react/components/organization/members/member.columns.tsx
sdks/js/packages/core/react/components/organization/members/member.types.tsx
sdks/js/packages/core/react/hooks/useOrganizationMembers.ts
sdks/js/pnpm-lock.yaml

This PR will add following:
1. show member roles in org member list table
2. display domain `created_at` in human readable format eg: `20 Oct 23, 03:38PM`

feat(sdk): show roles in org member list

---

cmd/serve.go
config/sample.config.yaml
core/authenticate/service.go
core/authenticate/strategy/mail_otp.go
go.mod
go.sum
pkg/mailer/dialer.go
pkg/mailer/mailer.go
sdks/js/packages/core/package.json
test/e2e/regression/authentication_test.go

- Added option to disable `STARTTLS` for smtp dialer
- Added additional e2e test to validate the flow

fix: mailotp code comparison was failing

---

pkg/server/server.go

This PR will fix the metrics count as currently, all metrics counts are 0.
passing Prometheus metric interceptor middleware as per the [example](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/providers/prometheus/v1.0.0/examples/server/main.go#L140)

fix: pass prometheus metric interceptor as middleware

---

billing/customer/service.go
billing/product/service.go
internal/api/v1beta1/billing_customer.go
internal/api/v1beta1/billing_product.go
internal/store/postgres/billing_customer_repository.go
internal/store/postgres/billing_product_repository.go
test/e2e/regression/billing_test.go

- fixes product update api call failing with provider id missing

feat: update billing customer API

---

sdks/js/packages/core/react/components/organization/billing/billing.module.css
sdks/js/packages/core/react/components/organization/billing/cycle-switch/index.tsx
sdks/js/packages/core/react/components/organization/billing/upcoming-billing-cycle.tsx
sdks/js/packages/core/react/components/organization/plans/helpers/index.ts
sdks/js/packages/core/react/components/organization/profile.tsx
sdks/js/packages/core/react/utils/index.ts
sdks/js/packages/core/src/types.ts

This PR will add support for plan interval cycle toggle.
users can switch plan interval from billing screen.

feat(sdk): add plan interval cycle toggle

---

ui/package-lock.json
ui/package.json
ui/src/containers/organisations.list/billingaccounts/tokens/add.tsx

This PR will add quantity field for token checkout in admin portal

feat(admin-ui): add quantity to token checkout

---

billing/customer/service.go
cmd/serve.go
internal/metrics/metrics.go
internal/metrics/stripe.go
pkg/server/interceptors/authorization.go
pkg/server/server.go

- changed authz permissions access for enable/disable org to platform owners

feat: exposing stripe api latency on prometheus endpoint

---

sdks/js/packages/core/react/components/avatar-upload/index.tsx
sdks/js/packages/core/react/components/organization/plans/pricing-column.tsx
sdks/js/packages/core/react/components/organization/tokens/transactions/columns.tsx
sdks/js/packages/core/react/components/organization/tokens/transactions/index.tsx
sdks/js/packages/core/react/index.ts

Fix transaction table caching and export avatar upload component.

fix(sdk): show checkout if user has no subscriptions.

---

billing/checkout/service.go
billing/customer/service.go
billing/invoice/service.go
billing/subscription/service.go
internal/metrics/stripe.go
internal/store/postgres/billing_checkout_repository.go

Added additional metrics to track sync latency between frontier and billing engine.

fix: skip processing applied checkouts

---

billing/subscription/service.go

Revert "fix: set empty plan id for subscription cancel"

---

sdks/js/packages/core/api-client/V1Beta1.ts
sdks/js/packages/core/api-client/data-contracts.ts

Related BE PR: [https://github.com/raystack/frontier/pull/724](https://github.com/raystack/frontier/pull/724)

feat: add client gen for org list API

---

sdks/js/packages/core/package.json
sdks/js/packages/sdk-demo/package.json
sdks/js/pnpm-lock.yaml
ui/package.json
ui/pnpm-lock.yaml

1. Updates frontier version in sdk-demo and admin to v0.30.1.
2. Minor package.json script fix.

chore (frontier): update version to v0.30.1

---

sdks/js/packages/core/package.json
sdks/js/packages/sdk-demo/package.json
ui/package.json

Increase apsara version in UI, sdk-demo and core.

chore: increase version apsara

---

ui/src/containers/groups.create/index.tsx
ui/src/containers/projects.create/index.tsx
ui/src/contexts/App.tsx

Set organisation API page_size to 1000 till filters are supported on the BE.

fix: set page size 1000 till filter is implemented in org list API

---

sdks/js/packages/core/api-client/V1Beta1.ts
sdks/js/packages/core/api-client/data-contracts.ts
sdks/js/packages/core/api-client/http-client.ts
ui/src/containers/invoices.list/index.tsx

invoice list gen client and add params to admin ui API call.

fix (ui): add invoice list params

---

sdks/js/packages/core/react/components/organization/api-keys/service-user/index.tsx
sdks/js/packages/core/react/components/organization/api-keys/service-user/styles.module.css

This PR will show the Basic token created from the token and ID.

feat(sdk): show basic token for api

---

sdks/js/packages/core/react/components/organization/api-keys/service-user/index.tsx

https://github.com/user-attachments/assets/1a7816f4-c21f-4ab0-9091-45d0bc362a42
This will update the copy icon after the successful full copy

fix(sdk): show check icon after copy in api token

---

sdks/js/packages/core/package.json

chore: upgrade apsara version

---

docker-compose.yml
sdks/js/packages/sdk-demo/Dockerfile
sdks/js/packages/sdk-demo/package-lock.json

- Adds support for using pg_dump to load data into spicedb postgres database
- spicedb needs the restored database to be repaired. Requires Postgres 15+
- Fix sdk-demo build

fix: docker-compose setup to start all services and sdk-demo

---

sdks/js/packages/core/react/hooks/usePreferences.ts
sdks/js/packages/core/react/index.ts

This PR exports the usePreferences hook

chore: export usePreferences hook

---

ui/package-lock.json
ui/package.json
ui/src/main.tsx
ui/src/pages/organizations/details/contexts/organization-context.tsx
ui/src/pages/organizations/details/index.tsx
ui/src/pages/organizations/details/layout/index.tsx
ui/src/pages/organizations/details/layout/invite-users-dialog.tsx
ui/src/pages/organizations/details/layout/layout.module.css
ui/src/pages/organizations/details/layout/navbar.tsx
ui/src/pages/organizations/details/side-panel/kyc-section.tsx
ui/src/pages/organizations/details/types.ts
ui/src/routes.tsx

This PR adds the invite user dialog from where admins can invite users to an org.
admins need to enter user email ids and role.
This PR also introduces an Org context as the roles and org data are fetched by root, and dialog can't access that data.

feat(admin_ui): add invite users dialog.

---

billing/checkout/service.go
sdks/js/packages/core/react/components/organization/billing/index.tsx
sdks/js/packages/core/react/components/organization/billing/payment-method.tsx
sdks/js/packages/core/react/contexts/FrontierContext.tsx

feat(sdk): disable address update button when kyc is completed

---

ui/package-lock.json
ui/package.json
ui/src/pages/organizations/details/layout/navbar.tsx
ui/src/pages/organizations/details/members/columns.tsx
ui/src/pages/organizations/details/projects/columns.tsx
ui/src/pages/organizations/details/projects/members/columns.tsx
ui/src/pages/organizations/details/side-panel/index.tsx
ui/src/pages/organizations/list/columns.tsx

This PR upgrades the apsara version in the admin ui.
This also uses the generated color in the Avatar.
The navbar will use the sub-menu in the organization details page in a dropdown.

chore(admin_ui): update apsara version to v0.43.0

---

billing/checkout/service.go

set the customer_update value to never if KYC is verified
https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-customer_update

fix: auto update address if kyc is not verified

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/components/Sidebar/index.tsx
ui/src/containers/preferences.list/details.tsx
ui/src/pages/organizations/details/layout/navbar.tsx
ui/src/pages/organizations/details/members/columns.tsx
ui/src/pages/organizations/details/members/members.module.css
ui/src/pages/organizations/details/projects/columns.tsx
ui/src/pages/organizations/details/projects/index.tsx
ui/src/pages/organizations/details/projects/members/add-members-dropdown.tsx
ui/src/pages/organizations/details/projects/members/columns.tsx
ui/src/pages/organizations/details/projects/members/index.tsx
ui/src/pages/organizations/details/projects/members/members.module.css
ui/src/pages/organizations/details/projects/projects.module.css
ui/src/pages/organizations/details/projects/useAddProjectMembers.tsx
ui/src/utils/constants.ts

This PR will add dropdowns to add members to a project.
1.  A dropdown is added to the project list page
2. Another dropdown is added to project members page.
This PR also updates the dropdowns in the project as the new dropdown is a breaking change.

feat(admin-ui): add dropdown to add users in project

---

sdks/js/packages/core/react/components/organization/api-keys/add.tsx
sdks/js/packages/core/react/components/organization/members/invite.tsx
sdks/js/packages/core/react/components/organization/teams/members/invite.tsx
sdks/js/packages/core/react/utils/index.ts

This PR fixes Select not working post migration

fix: select not working post migration

---

sdks/js/packages/core/react/components/organization/api-keys/add.tsx
sdks/js/packages/core/react/components/organization/api-keys/service-user/projects.tsx

This PR updates the default role of service user to `Project Owner` from `Project Viewer`.

fix(sdk): update service user role to owner in project

---

ui/src/pages/users/details/layout/membership-dropdown.tsx
ui/src/pages/users/details/layout/side-panel-membership.tsx
ui/src/pages/users/details/layout/side-panel.tsx
ui/src/pages/users/list/columns.tsx
ui/src/pages/users/list/list.tsx

This PR migrates the `SearchUsers` and `SearchUserOrganizations` APIs in the admin console to connect RPC.

feat(admin-ui): migrate users apis to connect rpc

---

pkg/server/connect_interceptors/session.go

Reverts raystack/frontier#1141

Revert "fix: cookie setup and cleanup in connect rpc server"

---

pkg/server/connect_interceptors/session.go

Reverts raystack/frontier#1157

Revert "Revert "fix: cookie setup and cleanup in connect rpc server""
